[build]
  base    = "frontend"
  command = "npm install && npm run build"
  publish = "dist"

# Single-page app: send all unknown routes to index.html
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Never cache index.html (so new builds show immediately)
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Expires       = "0"
    Pragma        = "no-cache"

# Also disable caching for these
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Expires       = "0"
    Pragma        = "no-cache"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Expires       = "0"
    Pragma        = "no-cache"

# Static assets can be cached hard
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
